export const DICTIONARY = {
    DayOne: [
        {english: "to park", russian: "парковаться", id: 1, img: '/images/dayOne/topark.jpeg'},
        {english: "to give", russian: "давать", id: 2, img: '/images/dayOne/togive.jpg'},
        {english: "to live", russian: "жить", id: 3, img: '/images/dayOne/tolive.jpg'},
        {english: "to drive", russian: "водить", id: 4, img: '/images/dayOne/todrive.jpg'},
        {english: "to take", russian: "брать", id: 5, img: '/images/dayOne/totake.jpg'},
        {english: "to get on", russian: "сесть (в автобус)", id: 6, img: '/images/dayOne/togeton.jpg',},
        {english: "to get off", russian: "выйты (из автобуса)", id: 7, img: '/images/dayOne/togetoff.jpg',},
        {english: "to be late", russian: "опоздать", id: 8, img: '/images/dayOne/tobelate.jpg'},
        {english: "to run", russian: "бежать", id: 9, img: '/images/dayOne/torun.jpg'},
        {english: "to sit", russian: "сидеть", id: 10, img: '/images/dayOne/tosit.jpeg'},
    ],
    DayTwo: [
        {english: "to forget", russian: "забыть", id: 11, img: '/images/dayTwo/toforget.jpg'},
        {english: "to wait for", russian: "ждать", id: 12, img: '/images/dayTwo/towaitfor.jpg'},
        {english: "to watch", russian: "смотреть", id: 13, img: '/images/dayTwo/towatch.jpeg'},
        {english: "to cross", russian: "пересикать", id: 14, img: '/images/dayTwo/tocross.jpeg'},
        {english: "to use", russian: "использовать", id: 15, img: '/images/dayTwo/touse.jpg',},
        {english: "to keep", russian: "хранить, держать", id: 16, img: '/images/dayTwo/tokeep.jpg',},
        {english: "to look for", russian: "искать", id: 17, img: '/images/dayTwo/tolookfor.jpg',},
        {english: "to go into", russian: "зайти", id: 18, img: '/images/dayTwo/togointo.jpg'},
        {english: "to read", russian: "читать", id: 19, img: '/images/dayTwo/toread.jpeg'},
        {english: "to turn", russian: "поворачивать", id: 20, img: '/images/dayTwo/totourn.jpg',},
    ],
    DayThree: [
        {english: "to get in the car", russian: "сесть в машину", id: 11, img: '/images/dayThree/togetinthecar.jpg'},
        {english: "to go out of the car", russian: "выйти из машины", id: 12, img: '/images/dayThree/togooutofthecar.jpg'},
        {english: "to open", russian: "открыть", id: 18, img: '/images/dayThree/toopen.jpeg'},
        {english: "to write", russian: "писать", id: 13, img: '/images/dayThree/towrite.jpeg'},
        {english: "to eat", russian: "кушать", id: 14, img: '/images/dayThree/toeat.jpg'},
        {english: "to speak", russian: "говорить", id: 15, img: '/images/dayThree/tospeak.jpg',},
        {english: "to take classes", russian: "заниматься", id: 16, img: '/images/dayThree/totakecalasses.jpg',},
        {english: "to worry", russian: "беспокоиться, волноваться", id: 17, img: '/images/dayThree/toworry.jpg',},
        {english: "to understand", russian: "понимать", id: 19, img: '/images/dayThree/tounderstand.jpg'},
        {english: "to enroll", russian: "записваться", id: 20, img: '/images/dayThree/toenroll.jpg',},
    ],
    DayFour: [
        {english: "to ask for", russian: "спрашвать", id: 11, img: '/images/dayFour/toaskfor.jpg'},
        {english: "to look at", russian: "Смотреть в, на", id: 12, img: '/images/dayFour/tolookat.jpg'},
        {english: "to make", russian: "делать", id: 13, img: '/images/dayFour/tomake.jpg'},
        {english: "Bench", russian: "скамейка", id: 14, img: '/images/dayFour/bench.jpg'},
        {english: "Newspaper", russian: "газета", id: 15, img: '/images/dayFour/newspaper.jpg',},
        {english: "Signs", russian: "знаки", id: 16, img: '/images/dayFour/signs.jpg'},
        {english: "Street", russian: "улица", id: 17, img: '/images/dayFour/street.jpg'},
        {english: "Classroom", russian: "класс", id: 18, img: '/images/dayFour/classroom.jpg'},
        {english: "Welcome", russian: "добро пожаловать", id: 19, img: '/images/dayFour/wolcome.jpg'},
        {english: "U-turn", russian: "разварот", id: 20, img: '/images/dayFour/u-turn.jpg'},
    ],
    DayFive: [
        {english: "Parking lot", russian: "парковка", id: 11, img: '/images/dayFive/parkinglot.jpg'},
        {english: "Grass", russian: "трава", id: 12, img: '/images/dayFive/grass.jpg'},
        {english: "Pencil", russian: "карандаш", id: 13, img: '/images/dayFive/pencel.jpg'},
        {english: "Page", russian: "страница", id: 14, img: '/images/dayFive/page.jpg'},
        {english: "Paper", russian: "бумага", id: 15, img: '/images/dayFive/paper.jpg'},
        {english: "Quickly", russian: "быстро", id: 16, img: '/images/dayFive/quickly.jpg'},
        {english: "Lunch", russian: "обед", id: 17, img: '/images/dayFive/luch.jpg'},
        {english: "Well", russian: "хорошо", id: 18, img: '/images/dayFive/well.jpg'},
        {english: "Room", russian: "комното, место", id: 19, img: '/images/dayFive/room.jpg'},
        {english: "Map", russian: "карта", id: 20, img: '/images/dayFive/map.jpg'},
    ],
    DaySix: [
        {english: "Maybe", russian: "возможно", id: 11, img: '/images/daySix/maybe.png'},
        {english: "Direction", russian: "напровление", id: 12, img: '/images/daySix/direction.jpg'},
        {english: "ActionAreaCard", russian: "карточка", id: 13, img: '/images/daySix/card.jpg'},
        {english: "Instruction", russian: "инструкция", id: 14, img: '/images/daySix/instruction.jpg'},
        {english: "To be right", russian: "быть правым", id: 15, img: '/images/daySix/toberight.jpg'},
        {english: "To type", russian: "печатать", id: 16, img: '/images/daySix/totype.jpg'},
        {english: "To spell", russian: "произности по буквам", id: 17, img: '/images/daySix/tospell.jpg'},
        {english: "To need", russian: "нуждаться", id: 18, img: '/images/daySix/toneed.jpg'},
        {english: "To want", russian: "хотеть", id: 19, img: '/images/daySix/towant.jpg'},
        {english: "To make noise", russian: "шумить", id: 20, img: '/images/daySix/tomakenoise.jpg'},
    ],
    DaySeven: [
        {english: "To cook", russian: "готовить", id: 11, img: '/images/daySeven/tocook.png'},
        {english: "To smoke", russian: "курить", id: 12, img: '/images/daySeven/tosmoke.jpg'},
        {english: "To learn", russian: "учить", id: 13, img: '/images/daySeven/tolearn.jpg'},
        {english: "To study", russian: "учиться", id: 14, img: '/images/daySeven/tostudy.jpg'},
        {english: "To teach", russian: "учить, проподовать", id: 15, img: '/images/daySeven/toteach.jpg'},
        {english: "To try", russian: "пробовать, пытаться", id: 16, img: '/images/daySeven/totry.jpg'},
        {english: "To hear", russian: "слышать", id: 17, img: '/images/daySeven/tohear.jpg'},
        {english: "To be tired", russian: "уставить", id: 18, img: '/images/daySeven/tobetired.jpg'},
        {english: "To listen to", russian: "слушать", id: 20, img: '/images/daySeven/tolistento.jpg'},
    ],
    DayEight: [
        {english: "To pay", russian: "платить", id: 11, img: '/images/dayEight/topay.jpg'},
        {english: "To buy", russian: "покупать", id: 12, img: '/images/dayEight/tobuy.jpg'},
        {english: "To practice", russian: "практиковаться", id: 13, img: '/images/dayEight/topractice.jpg'},
        {english: "To find", russian: "найти", id: 14, img: '/images/dayEight/tofind.jpeg'},
        {english: "To sleep", russian: "спать", id: 15, img: '/images/dayEight/tosleep.jpg'},
        {english: "To carry", russian: "носить", id: 16, img: '/images/dayEight/tocarry.jpg'},
        {english: "To move", russian: "переезжать", id: 17, img: '/images/dayEight/tomove.jpg'},
        {english: "To get up", russian: "вставать", id: 18, img: '/images/dayEight/togetup.jpg'},
        {english: "To come over", russian: "навещать", id: 19, img: '/images/dayEight/tocomeover.jpg'},
        {english: "Skills", russian: "навыки, умения", id: 20, img: '/images/dayEight/skills.jpg'},
    ],
    DayNine: [
        {english: "chemist's, pharmacy", russian: "аптека", id: 11, img: "/images/dayNine/chemist's.jpg"},
        {english: "a church", russian: "церковь", id: 12, img: '/images/dayNine/church.jpg'},
        {english: "a department store", russian: "универмаг", id: 13, img: '/images/dayNine/department_store.jpg'},
        {english: "a market", russian: "рынок", id: 14, img: '/images/dayNine/market.jpg'},
        {english: "a police station", russian: "полицейский участок", id: 15, img: '/images/dayNine/police_station.jpeg'},
        {english: "a post office", russian: "почтовое отделение", id: 16, img: '/images/dayNine/post_office.jpg'},
        {english: "a town hall", russian: "ратуша", id: 17, img: '/images/dayNine/town_hall.jpg'},
        {english: "an art gallery", russian: "художественная галерея", id: 18, img: '/images/dayNine/art_gallery.jpg'},
        {english: "a castle", russian: "замок", id: 19, img: '/images/dayNine/castle.jpg'},
        {english: "a palace", russian: "дворец", id: 20, img: '/images/dayNine/palace.jpg'},
    ],
    DayTen: [
        {english: "a zoo", russian: "зоопарк", id: 11, img: '/images/dayTen/zoo.jpg'},
        {english: "a bridge", russian: "мост", id: 12, img: '/images/dayTen/bridge.jpeg'},
        {english: "a river", russian: "река", id: 13, img: '/images/dayTen/river.jpg'},
        {english: "a road", russian: "дорога", id: 14, img: '/images/dayTen/road.jpg'},
        {english: "a square", russian: "площадь", id: 15, img: '/images/dayTen/square.jpg'},
        {english: "a street", russian: "улица", id: 16, img: '/images/dayTen/street.jpg'},
        {english: "a bus station", russian: "автовокзал", id: 17, img: '/images/dayTen/bus_station.jpg'},
        {english: "a car park", russian: "автостоянка", id: 18, img: '/images/dayTen/car_park.jpg'},
        {english: "a railway station", russian: "навещать", id: 19, img: '/images/dayTen/railway_station.jpg'},
        {english: "a theatre", russian: "театр", id: 20, img: '/images/dayTen/theatre.jpg'},
    ],
    DayEleven: [
        {english: "a cathedral", russian: "Кафедральный собор", id: 11, img: '/images/dayEleven/cathedral.jpg'},
        {english: "a mosque", russian: "мечеть", id: 12, img: '/images/dayEleven/mosque.jpg'},
        {english: "a synagogue", russian: "синагога", id: 13, img: '/images/dayEleven/synagogue.jpg'},
        {english: "a temple", russian: "храм", id: 14, img: '/images/dayEleven/temple.jpg'},
        {english: "arrivals", russian: "прибытие", id: 14, img: '/images/dayEleven/arrivals.jpg'},
        {english: "bag drop", russian: "сдача багажа", id: 14, img: '/images/dayEleven/bag_drop.jpg'},
        {english: "baggage reclaim", russian: "получение багажа", id: 14, img: '/images/dayEleven/baggage_reclaim.jpg'},
        {english: "reclaim", russian: "вернуть, восстановить", id: 14, img: '/images/dayEleven/reclaim.png'},
        {english: "check in", russian: "регистрироваться", id: 14, img: '/images/dayEleven/check_in.jpg'},
        {english: "customs", russian: "таможня", id: 14, img: '/images/dayEleven/customs.jpg'},
        {english: "departures", russian: "Отправления", id: 14, img: '/images/dayEleven/departures.jpg'},
        {english: "gates", russian: "ворота", id: 14, img: '/images/dayEleven/gates.jpeg'},
        {english: "security check", russian: "проверка безопасности", id: 14, img: '/images/dayEleven/security_check.jpeg'},
        {english: "trolley", russian: "тележка", id: 14, img: '/images/dayEleven/trolley.jpg'},
    ],
};


export const IRREGULAR_VERBS = [
    {id: 1, BaseForm: "awake", PastSimple: "awoke", Russian: "бодрствующий"},
    {id: 2, BaseForm: "be", PastSimple: "was/were", Russian: "был"},
    {id: 3, BaseForm: "beat", PastSimple: "beat", Russian: "бить, ударить"},
    {id: 4, BaseForm: "bite", PastSimple: "bit", Russian: "кусать"},
    {id: 5, BaseForm: "begin", PastSimple: "began", Russian: "начинать"},
    {id: 6, BaseForm: "blow", PastSimple: "blew", Russian: "дуть"},
    {id: 7, BaseForm: "break", PastSimple: "broke", Russian: "ломать"},
    {id: 8, BaseForm: "bring", PastSimple: "brought", Russian: "приносить"},
    {id: 9, BaseForm: "build", PastSimple: "built", Russian: "строить"},
    {id: 10, BaseForm: "buy", PastSimple: "bought", Russian: "купить"},
    {id: 11, BaseForm: "become", PastSimple: "became", Russian: "стали"},
    {id: 12, BaseForm: "can", PastSimple: "could", Russian: "Можно"},
    {id: 13, BaseForm: "catch", PastSimple: "caught", Russian: "ловить"},
    {id: 14, BaseForm: "come", PastSimple: "came", Russian: "прийти"},
    {id: 15, BaseForm: "do", PastSimple: "did", Russian: "делать"},
    {id: 16, BaseForm: "drink", PastSimple: "drank", Russian: "пить"},
    {id: 17, BaseForm: "drive", PastSimple: "drove", Russian: "водить машину"},
    {id: 18, BaseForm: "eat", PastSimple: "ate", Russian: "есть"},
    {id: 19, BaseForm: "fall", PastSimple: "fell", Russian: "падение"},
    {id: 20, BaseForm: "feel", PastSimple: "felt", Russian: "Чувствовать"},
    {id: 21, BaseForm: "find", PastSimple: "found", Russian: "найти"},
    {id: 22, BaseForm: "fli", PastSimple: "flew", Russian: "летать"},
    {id: 23, BaseForm: "forget", PastSimple: "forgot", Russian: "забывать"},
    {id: 24, BaseForm: "get", PastSimple: "получить", Russian: "купить"},
    {id: 25, BaseForm: "give", PastSimple: "gave", Russian: "давать"},
    {id: 26, BaseForm: "go", PastSimple: "went", Russian: "идти"},
    {id: 27, BaseForm: "have", PastSimple: "had", Russian: "иметь"},
    {id: 28, BaseForm: "hear", PastSimple: "heard", Russian: "слышать"},
    {id: 29, BaseForm: "know", PastSimple: "knew", Russian: "знать"},
    {id: 30, BaseForm: "leave", PastSimple: "left", Russian: "оставлять"},
    {id: 31, BaseForm: "lose", PastSimple: "lost", Russian: "терять"},
    {id: 32, BaseForm: "make", PastSimple: "made", Russian: "делать"},
    {id: 33, BaseForm: "meet", PastSimple: "met", Russian: "встретиться"},
    {id: 34, BaseForm: "pay", PastSimple: "paid", Russian: "платить"},
    {id: 35, BaseForm: "put", PastSimple: "put", Russian: "помещать"},
    {id: 36, BaseForm: "read", PastSimple: "read", Russian: "читать"},
    {id: 37, BaseForm: "run", PastSimple: "ran", Russian: "run"},
    {id: 38, BaseForm: "say", PastSimple: "said", Russian: "сказать"},
    {id: 39, BaseForm: "see", PastSimple: "saw", Russian: "видеть"},
    {id: 40, BaseForm: "send", PastSimple: "sent", Russian: "Отправить"},
    {id: 41, BaseForm: "sing", PastSimple: "sang", Russian: "петь"},
    {id: 42, BaseForm: "sit", PastSimple: "sat", Russian: "сидеть"},
    {id: 43, BaseForm: "sleep", PastSimple: "slept", Russian: "спать"},
    {id: 44, BaseForm: "speak", PastSimple: "spoke", Russian: "говорить"},
    {id: 45, BaseForm: "spend", PastSimple: "spent", Russian: "проводить"},
    {id: 46, BaseForm: "stand", PastSimple: "stood", Russian: "стоять"},
    {id: 47, BaseForm: "swim", PastSimple: "swam", Russian: "плавать"},
    {id: 48, BaseForm: "teach", PastSimple: "taught", Russian: "учить"},
    {id: 49, BaseForm: "take", PastSimple: "took", Russian: "брать"},
    {id: 50, BaseForm: "tell", PastSimple: "told", Russian: "сказать"},
    {id: 51, BaseForm: "think", PastSimple: "thought", Russian: "считать"},
    {id: 52, BaseForm: "understand", PastSimple: "understood", Russian: "понять"},
    {id: 53, BaseForm: "woke", PastSimple: "woken", Russian: "проснулся"},
    {id: 54, BaseForm: "wear", PastSimple: "wore", Russian: "носить"},
    {id: 55, BaseForm: "win", PastSimple: "won", Russian: "победить"},
    {id: 56, BaseForm: "write", PastSimple: "wrote", Russian: "записывать"},
]
